### ISSUE TITLE
WinRT COMException

### ISSUE THREAD

**Issue by luojunyuan** [ErogeHelper/ErogeHelper#16]
```
ErogeHelper v0.0.9.2 - UI-Fatal 错误
System.Runtime.InteropServices.COMException: 找不到元素。 (0x80070490)
系统版本: Windows 10 1507 X64
由 `WinRT.Runtime` 造成
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.UI.Notifications.IToastNotificationHistory.global::Windows.UI.Notifications.IToastNotificationHistory.Clear(String applicationId)
   at Windows.UI.Notifications.ToastNotificationHistory.Clear(String applicationId)
   at CommunityToolkit.WinUI.Notifications.ToastNotificationHistoryCompat.Clear()
   at ErogeHelper.App.Terminate(Int32 exitCode) in C:\Users\k1mlka\source\repos\ErogeHelper\ErogeHelper\App.xaml.cs:line 99
   at ErogeHelper.App.<>c.<.ctor>b__1_0(Object _, StartupEventArgs startupEvent) in C:\Users\k1mlka\source\repos\ErogeHelper\ErogeHelper\App.xaml.cs:line 51
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by luojunyuan** [comment]
让EH主动弹一次窗能够永久解决这个问题（如EH运行的情况下再次打开ErogeHelper.exe程序）

**Comment by luojunyuan** [comment]
早期win10 首次运行程序在退出程序时调用清空消息toast会报错“找不到元素”，可能是因为unpackage应用没有注册toast相关原因，当show toast过后恢复正常。
1511 也有同样问题，catch 一下当作解决

**Comment by luojunyuan** [comment]
white dot刚运行不见了，解决这个问题后又冒出来了，焯！
